name: Tests

on:
  pull_request:
  push:
    branches:
      - master


jobs:
  qa:
    strategy:
      matrix:
        php: [ '7.4','8.0','8.1','8.2','8.3','8.4' ]
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          coverage: xdebug
          tools: composer:v2

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-interaction

      - name: qa target
        run: vendor/bin/phing qa
